AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 120
